language: cpp
compiler: gcc
sudo: false

addons:
    apt:
        sources:
            # new boost
            - boost-latest
            # new gcc
            - ubuntu-toolchain-r-test
            # new cairo
        packages:
            - cmake
            - g++-4.8
            - libboost1.55-all-dev
            - libcairo2-dev
            - liblog4cpp5-dev
            - libpng12-dev


before_install:
  # TODO: do we need a replacement for this, or is new cairo new enough?
  # new cairo
  # - sudo add-apt-repository --yes ppa:ricotz/testing

  #if GCC
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

notifications:
  email:
    recipients:
      - alacarte-fail@mixaill.tk
    on_success: change
    on_failure: always
